name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: python setup
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[s3,test]"

    - name: run tests
      run: |
        pytest --cov=cachetools_ext test --cov-report=xml

    - name: upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
